<?php
/**
 * Add a new user group in the application
 *
 * @category admin
 * @package admin_views
 * @subpackage admin_views_groups
 * @copyright Copyright (c) 2011, Morteza Milani
 */
$config = array();
$viewConfig = array();

$viewConfig['pageTitle'] = 'Submission';

$viewConfig['columnNames'] = array(
    'Description'
);
$viewConfig['columnIndexes'] = array(
    'submission_desc'
);

echo $this->partial('partials/default-view.phtml',
	array(
    	'config'  => $viewConfig,
        'item'    => $this->item,
	    'boxsize' => '75'
    )
);

$config['pageTitle'] = 'Attachments';
$config['emptyMessage'] = 'No Attachment.';
$config['linkRouter'] = array(
    'defaultParams'	=> array('assignmentid'=>$this->assignmentId,'problemid'=>$this->problemId,'classid'=>$this->classId,'submissionid'=>$this->answerId)
);
// additional actions
$config['additionalActions'] = array(
    'downloadAttach' => array(
        'action'		=> 'downloadattachment',
        'controller'	=> 'submission',
        'title'			=> 'Download',
        'link_class'	=> 'ico',
        'img_alt'		=> 'Download',
        'img_url'		=> '/images/led-ico/download.png',
        'parameter'		=> true,
        'parameter_index'=> 'submission_file_unique'
    ),
 	'deleteAttach' => array(
        'action'		=> 'deleteattachment',
        'controller'	=> 'submission',
        'title'			=> 'Delete',
        'link_class'	=> 'ico',
        'img_alt'		=> 'Delete',
        'img_url'		=> '/images/led-ico/cross.png',
        'parameter'		=> true
    ),
);
// column names & indexes
$config['columnNames'] = array(
    'Filename'
);
$config['columnIndexes'] = array(
    'submission_file_name'
);
// configure the permissions
$config['linkOrder'] = array('downloadAttach', 'deleteAttach');

echo $this->partial('partials/attachment-listing.phtml', 
    array(
    	'config'        => $config,
        'attachments'	=> $this->attachments,
        'id'			=> $this->answerId,
        'controllerName'=> 'submission'
    )
);

$config = array();
$config['pageTitle'] = 'Grade Submission';
echo $this->partial('partials/default-add-edit.phtml', 
    array(
        'form' => $this->form,
    	'config' => $config,
        'boxsize'	=> '75'
    )
);

?>