<?php
/**
 * Add a new user group in the application
 *
 * @category admin
 * @package admin_views
 * @subpackage admin_views_groups
 * @copyright Copyright (c) 2011, Morteza Milani
 */
$config = array();
$config['pageTitle'] = 'Add new assignment';
echo $this->partial('partials/default-add-edit.phtml', 
array(
    'form' => $this->form, 'config' => $config
));
//echo $this->partial('partials/assignment-add-script.phtml');
