<?php
/**
 * Delete an user group
 *
 * @category admin
 * @package admin_views
 * @subpackage admin_views_groups
 * @copyright Copyright (c) 2011, Morteza Milani
 */
$config = array();
$config['pageTitle'] = sprintf('Delete course "%s"', $this->item['course_name']);
$config['areYouSureMessage'] = sprintf(
'Are you sure you want to delete course "%s"?', $this->item['course_name']);
// column names & indexes
$config['columnNames'] = array(
    'Course Name'
);
$config['columnIndexes'] = array(
    'course_name'
);
echo $this->partial('partials/default-delete.phtml', 
array(
    'form' => $this->form, 'config' => $config, 'item' => $this->item
));