<?php
/**
 * Displays the forbidden error
 *
 * @category admin
 * @package admin_views
 * @subpackage admin_views_error
 * @copyright Copyright (c) 2011, Morteza Milani
 */
?>
<div class="box box-100"><!-- box full-width -->
<div class="boxin">
<div id="errorpage" class="clearfix">
<h1>Forbidden</h1>
<p>You do not have enough privileges to access the requested resource.</p>
<p><a class="alt" href="javascript:history.back();">← Go back</a></p>
</div>
</div>
</div>