<?php
/**
 * View for the login action
 *
 * @category admin
 * @package admin_views
 * @subpackage admin_views_profile
 * @copyright Copyright (c) 2011, Morteza Milani
 */
?>
<div class="inner-form">
	<?php echo $this->flashMessenger();?>
    <?php if( isset($this->error) && !isset($this->inactive)):?>
    <div class="msg msg-error">
		<p><?php echo '<strong>'.$this->t('Login failed').'</strong>.<br />'.$this->t('Please check that you wrote your Username and Password correctly').'.';?></p>
	</div>
    <?php endif;?>
    <?php if( isset($this->inactive) ):?>
    <div class="msg msg-error">
		<p><?php echo '<strong>'.$this->t('Login failed').'</strong>.<br />'.$this->t('Your account is deactivated. Contact Administrator').'.';?></p>
	</div>
    <?php endif;?>
    <?php echo $this->form;?>
</div>
