<?php
/**
 * Delete an user 
 *
 * @category admin
 * @package admin_views
 * @subpackage admin_views_users
 * @copyright Copyright (c) 2011, Morteza Milani
 */
$config = array();
$config['pageTitle'] = 'Delete student';
$config['areYouSureMessage'] = 'Are you sure you want to delete student?';
// column names & indexes
$config['columnNames'] = array(
    'Student Number', 'First name', 'Last name'
);
$config['columnIndexes'] = array(
    'username', 'firstname', 'lastname'
);
echo $this->partial('partials/default-delete.phtml', 
        array(
    		'form' => $this->form,
        	'config' => $config,
        	'item' => $this->item
        )
     );