<?php
/**
 * Edit existing problem
 *
 * @category admin
 * @package admin_views
 * @subpackage admin_views_groups
 * @copyright Copyright (c) 2011, Morteza Milani
 */

$config = array();
$config['pageTitle'] = 'Edit problem';

echo $this->partial('partials/default-add-edit.phtml', 
    array(
        'form' => $this->form,
    	'config' => $config,
        'boxsize'	=> '75'
    )
);

$config['pageTitle'] = 'Attachments';
$config['emptyMessage'] = 'No Attachment.';
$config['linkRouter'] = array(
    'defaultParams'	=> array(
    	'classid'         => $this->classId,
        'assignmentid'    => $this->assignmentId,
        'problemid'		  => $this->problemId
    )
);
// additional actions
$config['additionalActions'] = array(
    'downloadAttach' => array(
        'action'		=> 'downloadattachment',
        'controller'	=> 'problem',
        'title'			=> 'Download',
        'link_class'	=> 'ico',
        'img_alt'		=> 'Download',
        'img_url'		=> '/images/led-ico/download.png',
        'parameter'		=> true,
        'parameter_index'=> 'file_unique',
        'parameter_name'=> 'file'
    ),
 	'deleteAttach' => array(
        'action'		=> 'deleteattachment',
        'controller'	=> 'problem',
        'title'			=> 'Delete',
        'link_class'	=> 'ico',
        'img_alt'		=> 'Delete',
        'img_url'		=> '/images/led-ico/cross.png',
        'parameter'		=> true,
        'parameter_index'	=> 'file_id'
    ),
);
// column names & indexes
$config['columnNames'] = array(
    'Filename'
);
$config['columnIndexes'] = array(
    'file_name'
);

// configure the permissions
$config['linkOrder'] = array('downloadAttach', 'deleteAttach');

echo $this->partial('partials/attachment-listing.phtml', 
    array(
    	'config'        => $config,
        'attachments'	=> $this->attachments,
        'id'			=> $this->problemId,
        'classId'		=> $this->classId
    )
);
